version: '3'

services:
  angular-app:
    hostname: modakira.com
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4000:80" # Lokal:4000 → Container:80 (NGINX)
    networks:
      - frontend-net
    restart: unless-stopped

networks:
  frontend-net:
    external: true
